# pnpm-workspace.yaml
packages:
  # Inclui os pacotes dentro da pasta frontend (mobile e web)
  - 'frontend/*'
  # Inclui o pacote backend
  - 'backend'
  # Inclui o pacote common com schemas compartilhados
  - 'common'
